# Generated by Django 5.1 on 2024-09-12 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="name",
            new_name="nombre",
        ),
    ]
