# Generated by Django 5.1 on 2024-09-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0002_evento_f_creacion_organizador_f_creacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizador",
            name="email",
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organizador",
            name="password",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
