# Generated by Django 5.1 on 2024-09-11 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0003_organizador_email_organizador_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizador",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
