# Generated by Django 5.1 on 2024-09-11 16:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0004_organizador_last_login"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="organizador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RemoveField(
            model_name="evento",
            name="f_creacion",
        ),
        migrations.AddField(
            model_name="evento",
            name="fecha",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="evento",
            name="fecha_creacion",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name="Organizador",
        ),
    ]
